### ISSUE TITLE
Make release to easier download

### ISSUE THREAD

**Issue by radeno** [vhyza/lemmagen-lexicons#1]
Hey,

we are using Lemmagen in Elasticsearch as Docker image.
For easier making docker image is to download whole repository as ZIP file than getting every language with wget/curl.

Any chance to have it as ZIP release?

**Comment by vhyza** [comment]
Here you go https://github.com/vhyza/lemmagen-lexicons/releases/tag/v1.0 💁‍♂️

**Comment by radeno** [comment]
@vhyza thank you :)
